package taskmanager;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

/** Writes an Obsidian-friendly, self-contained Markdown task dashboard. */
public final class MarkdownExporter {
    private MarkdownExporter() {
    }

    public static void write(Path output, Collection<Task> sourceTasks) throws IOException {
        List<Task> tasks = new ArrayList<>();
        if (sourceTasks != null) {
            for (Task task : sourceTasks) {
                if (task != null) {
                    tasks.add(task);
                }
            }
        }
        tasks.sort(Comparator.comparing(Task::isCompleted)
                .thenComparing(MarkdownExporter::dueDateKey)
                .thenComparing(Task::name, String.CASE_INSENSITIVE_ORDER));

        long completed = tasks.stream().filter(Task::isCompleted).count();
        long active = tasks.size() - completed;
        StringBuilder markdown = new StringBuilder();
        markdown.append("# Task Dashboard\n\n");
        markdown.append("Generated by Task Manager. Local edits are not written back to the source export.\n\n");
        markdown.append("## Summary\n\n");
        markdown.append("- Total: ").append(tasks.size()).append('\n');
        markdown.append("- Active: ").append(active).append('\n');
        markdown.append("- Completed: ").append(completed).append("\n\n");
        appendSection(markdown, "Active tasks", tasks, false);
        appendSection(markdown, "Completed tasks", tasks, true);

        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(output, markdown.toString(), StandardCharsets.UTF_8);
    }

    private static void appendSection(StringBuilder markdown, String title, List<Task> tasks, boolean completed) {
        markdown.append("## ").append(title).append("\n\n");
        boolean found = false;
        for (Task task : tasks) {
            if (task.isCompleted() != completed) {
                continue;
            }
            found = true;
            markdown.append("- [").append(completed ? 'x' : ' ').append("] ")
                    .append(escape(task.name()));
            if (!task.dueDate().isBlank()) {
                markdown.append(" — due ").append(escape(task.dueDate()));
            }
            appendMetadata(markdown, "importance", task.importance());
            appendMetadata(markdown, "urgency", task.urgency());
            appendMetadata(markdown, "project", task.project());
            appendMetadata(markdown, "areas", task.areas());
            markdown.append(" <!-- task-id:").append(escapeComment(task.id())).append(" -->\n");
        }
        if (!found) {
            markdown.append("_None_\n");
        }
        markdown.append('\n');
    }

    private static void appendMetadata(StringBuilder markdown, String label, String value) {
        if (value != null && !value.isBlank()) {
            markdown.append(" · ").append(label).append(": ").append(escape(value));
        }
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("\n", " ").replace("\r", " ").replace("|", "\\|");
    }

    private static String escapeComment(String value) {
        return value == null ? "" : value.replace("--", "-");
    }

    private static LocalDate dueDateKey(Task task) {
        return TaskDates.parse(task.dueDate()).orElse(LocalDate.MAX);
    }
}
